import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-600 h-16 text-white flex items-center justify-center font-bold text-2xl">Header </div>
        <main className="flex min-h-screen flex-col items-center justify-between p-4 ">
          {children}
        </main>
        <div className="bg-gray-600 h-16 text-white flex items-center justify-center font-bold text-2xl">Footer</div>
      </body>
    </html>
  );
}
